# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20170714_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pullrequest',
            name='last_build',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
