# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
        ('dashboard', '0002_auto_20170718_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=150, unique=True)),
                ('version', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_releases', to='jira.JiraClient')),
            ],
        ),
        migrations.CreateModel(
            name='ReleaseStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=150)),
                ('count', models.IntegerField()),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='dashboard.Release')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='release',
            unique_together=set([('project', 'version')]),
        ),
    ]
