# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20170719_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='project',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='release',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
