# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira', '0001_initial'),
        ('dashboard', '0007_pullrequest_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=1000)),
                ('key', models.CharField(max_length=150, unique=True)),
                ('url', models.TextField()),
                ('project', models.CharField(max_length=150)),
                ('status', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='SprintIssueAssignee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=500)),
                ('avatar', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='SprintIssueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
                ('icon', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='sprintissue',
            name='assignee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dashboard.SprintIssueAssignee'),
        ),
        migrations.AddField(
            model_name='sprintissue',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_sprint', to='jira.JiraClient'),
        ),
        migrations.AddField(
            model_name='sprintissue',
            name='issue_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='dashboard.SprintIssueType'),
        ),
    ]
