# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BitbucketClient',
            fields=[
                ('baseclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bitbucket.BaseClient')),
                ('password', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('bitbucket.baseclient',),
        ),
        migrations.CreateModel(
            name='GithubClient',
            fields=[
                ('baseclient_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bitbucket.BaseClient')),
                ('token', models.TextField()),
            ],
            bases=('bitbucket.baseclient',),
        ),
    ]
